 ;;; personal.el --- Emacs Prelude: Personal settings
;;
;;; Commentary:
;; Personal settings to augment those of Prelude
;; Install Emacs through homebrew with --cocoa --srgb

;;; Code:

;;; make cursor style bar
(setq-default cursor-type 'box)

(defun cdadar/reset-frame-size (&optional frame)
  "重设窗体大小"
  (interactive)
  (when frame
    (select-frame frame))
  (progn (set-frame-width (selected-frame) 120)
         (set-frame-height (selected-frame) 50)))

(cdadar/reset-frame-size)

(add-hook 'after-make-frame-functions 'cdadar/reset-frame-size)
(add-hook 'window-setup-hook 'cdadar/reset-frame-size)


;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(progn
  (setq face-font-rescale-alist nil)
  (set-face-attribute
   'default nil
   :font (font-spec :name "Hack"
                    :weight 'normal
                    :slant 'normal
                    :size 11.5))
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font
     "fontset-default"
     charset
     (font-spec :name "思源黑体 CN"
                :weight 'normal
                :slant 'normal
                :size 13.5))))


(provide 'init-personal)
;;; personal.el ends here
