 ;;; personal.el --- Emacs Prelude: Personal settings
;;
;;; Commentary:
;; Personal settings to augment those of Prelude
;; Install Emacs through homebrew with --cocoa --srgb

;;; Code:

;;; make cursor style bar
(setq-default cursor-type 'box)

(progn (set-frame-width (selected-frame) 120)
       (set-frame-height (selected-frame) 50))

;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(progn
  (setq face-font-rescale-alist nil)
  (set-face-attribute
   'default nil
   :font (font-spec :name "Hack"
                    :weight 'normal
                    :slant 'normal
                    :size 11.5))
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font
     "fontset-default"
     charset
     (font-spec :name "思源黑体 CN"
                :weight 'normal
                :slant 'normal
                :size 13.5))))

(provide 'init-personal)
;;; personal.el ends here
