name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs_version:
          - 24.4
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules && git submodule update --init --recursive

    - uses: actions/checkout@v1
    - name: Check startup
      run: ./test-startup.sh
